Repository bounswe/bounswe2022group3, pull requests merged in 2022-11, with the labels that each got.

#341 Mobile/refresh-indicator
  app/mobile/lib/classes/course/course.dart
  app/mobile/lib/services/course_service.dart
  app/mobile/lib/view/course/coursepage.dart
  app/mobile/lib/view/home/course_tile.dart
  app/mobile/lib/view/home/homepage.dart
  app/mobile/pubspec.yaml
Labels: mobile

#340 Mobile/coursepage
  app/mobile/lib/locator.config.dart
  app/mobile/lib/services/content_service.dart
  app/mobile/lib/services/locator.dart
  app/mobile/lib/view/course/coursepage.dart
  app/mobile/lib/view/course/mock_tile.dart
Labels: enhancement, effort: low, mobile

#335 populate only references and remove unnecessary fields from returns of enrollment and course functions
  app/server/src/routes/course/course.controller.js
  app/server/src/routes/enrollment/enrollment.controller.js
Labels: backend

#364 Backend: User schema update
  app/server/src/models/tokens/tokens.model.js
  app/server/src/models/user/user.model.js
  app/server/src/routes/user/user.controller.js
  app/server/src/routes/user/user.validate.js
  app/server/src/services/auth.js
Labels: backend

#354 start db creation script
  app/server/src/services/createDB.js
Labels: backend

#371 Backend: user schema update
  app/server/src/routes/user/user.controller.js
  app/server/src/routes/user/user.route.js
  app/server/src/routes/user/user.validate.js
  app/server/src/services/email/email.js
Labels: backend

#379 Backend/resource m2 specs
  app/server/src/models/resource/resource.model.js
  app/server/src/models/topic/topic.model.js
  app/server/src/routes/resource/resource.controller.js
  app/server/src/routes/resource/resource.route.js
  app/server/src/routes/resource/resource.validate.js
  app/server/src/routes/space/space.controller.js
  app/server/src/routes/topic/topic.controller.js
  app/server/src/routes/topic/topic.route.js
Labels: backend

#385 discusson changes for 2nd api specification
  app/server/src/models/comment/comment.model.js
  app/server/src/models/discussion/discussion.model.js
  app/server/src/models/user/user.model.js
  app/server/src/routes/comment/comment.controller.js
  app/server/src/routes/comment/comment.validate.js
  app/server/src/routes/discussion/discussion.controller.js
  app/server/src/routes/discussion/discussion.route.js
  app/server/src/routes/discussion/discussion.validate.js
  app/server/src/routes/space/space.controller.js
  app/server/src/routes/space/space.route.js
Labels: backend

#387 Mobile/api-specification-v2
  app/mobile/lib/classes/chapter/chapter.dart
  app/mobile/lib/classes/chapter/chapter.g.dart
  app/mobile/lib/classes/course/course.dart
  app/mobile/lib/classes/course/course.g.dart
  app/mobile/lib/classes/resource/resource.dart
  app/mobile/lib/classes/resource/resource.g.dart
  app/mobile/lib/classes/user/user.dart
  app/mobile/lib/classes/user/user.g.dart
  app/mobile/lib/main.dart
  app/mobile/lib/services/course_service.dart
  app/mobile/lib/services/user_service.dart
  app/mobile/lib/view/course/coursepage.dart
Labels: status: review-needed, mobile

#345 Mobile/deep links
  app/mobile/android/app/build.gradle
  app/mobile/android/app/src/main/AndroidManifest.xml
  app/mobile/lib/services/user_service.dart
  app/mobile/lib/view/dashboard_view.dart
  app/mobile/lib/view/intro/intro.dart
  app/mobile/pubspec.lock
  app/mobile/pubspec.yaml
Labels: priority: low, effort: low, mobile

#376 Mobile/markdown editor
  app/mobile/lib/view/widgets/markdown_input.dart
  app/mobile/pubspec.lock
  app/mobile/pubspec.yaml
Labels: enhancement, priority: moderate, effort: moderate, status: review-needed, mobile

#362 [Frontend]: GDPR check button + resource detail page
  app/client/components/CourseCard/CourseCard.jsx
  app/client/components/CourseCard/CourseCard.module.scss
  app/client/components/Rating/Rating.jsx
  app/client/components/Rating/Rating.module.scss
  app/client/pages/my/spaces/[space_id]/[resource].js
  app/client/pages/my/spaces/[space_id]/createResource.js
  app/client/pages/my/spaces/[space_id]/resources.js
  app/client/pages/user/register.js
  app/client/public/math.jpeg
  app/client/styles/my/resource_detail.module.scss
  app/client/styles/user/form.module.scss
Labels: frontend

#355 frontend/added discussion table
  app/client/pages/my/spaces/[space_id]/discussion/[discussion_id].js
  app/client/pages/my/spaces/[space_id]/discussions.js
  app/client/styles/my/discussions.module.scss
Labels: frontend

#386 Backend/unit tests
  app/server/jest.config.js
  app/server/package.json
  app/server/src/.env.example
  app/server/src/routes/user/user.controller.js
  app/server/src/routes/user/user.route.js
  app/server/src/routes/user/user.validate.js
  app/server/src/setup-tests.js
  app/server/src/tests/user/user.test.js
  app/server/src/tests/utils/db.js
Labels: backend

#382 Backend/get param validation for space, topic and resource
  app/server/src/routes/resource/resource.route.js
  app/server/src/routes/resource/resource.validate.js
  app/server/src/routes/space/space.route.js
  app/server/src/routes/space/space.validate.js
  app/server/src/routes/topic/topic.route.js
  app/server/src/routes/topic/topic.validate.js
Labels: backend
