Repository bounswe/bounswe2022group3, pull requests merged in 2022-10, with the labels that each got.

#277 frontend for registration and login without backend
  app/client/.eslintrc.json
  app/client/.gitignore
  app/client/README.md
  app/client/components/Button/Button.jsx
  app/client/components/Button/Button.module.scss
  app/client/components/Loading/Loading.jsx
  app/client/components/Loading/Loading.module.scss
  app/client/layouts/auth/AuthLayout.jsx
  app/client/layouts/auth/AuthLayout.module.scss
  app/client/next.config.js
  app/client/package-lock.json
  app/client/package.json
  app/client/pages/_app.js
  app/client/pages/_document.js
  app/client/pages/index.js
  app/client/pages/user/login.js
  app/client/pages/user/register.js
  app/client/public/education.png
  app/client/public/favicon.ico
  app/client/public/login.png
  app/client/styles/globals.scss
  app/client/styles/user/form.module.scss
  app/client/styles/variables.scss
  app/client/yarn.lock
Labels: status: review-needed, frontend

#294 Backend: User/PersonalInformation
  app/server/src/models/personalInfo/personalInfo.model.js
  app/server/src/routes/api.js
  app/server/src/routes/userProfile/userProfile.controller.js
  app/server/src/routes/userProfile/userProfile.route.js
  app/server/src/routes/userProfile/userProfile.validate.js
Labels: backend

#310 add name, surname to return of login and confirmEmail
  app/server/src/routes/user/user.controller.js
Labels: backend

#309 Frontend: connecting frontend to backend (login, register, confirm email)
  app/client/next.config.js
  app/client/package.json
  app/client/pages/confirmation/[token].js
  app/client/pages/user/login.js
  app/client/pages/user/register.js
  app/client/styles/confirmation/styles.module.scss
  app/client/styles/globals.scss
Labels: effort: moderate, frontend

#317 Mobile/backend connection
  app/mobile/ios/Flutter/Debug.xcconfig
  app/mobile/ios/Flutter/Release.xcconfig
  app/mobile/ios/Podfile
  app/mobile/ios/Podfile.lock
  app/mobile/ios/Runner.xcodeproj/project.pbxproj
  app/mobile/ios/Runner.xcworkspace/contents.xcworkspacedata
  app/mobile/lib/classes/course/course.dart
  app/mobile/lib/classes/course/course.g.dart
  app/mobile/lib/classes/user/login.dart
  app/mobile/lib/classes/user/login.g.dart
  app/mobile/lib/classes/user/refresh.dart
  app/mobile/lib/classes/user/refresh.g.dart
  app/mobile/lib/classes/user/user.dart
  app/mobile/lib/classes/user/user.g.dart
  app/mobile/lib/locator.config.dart
  app/mobile/lib/main.dart
  app/mobile/lib/resources/constants.dart
  app/mobile/lib/services/course_service.dart
  app/mobile/lib/services/dio_service.dart
  app/mobile/lib/services/locator.dart
  app/mobile/lib/services/persistence_service.dart
  app/mobile/lib/services/user_service.dart
  app/mobile/lib/view/home/appbar.dart
  app/mobile/lib/view/home/course_tile.dart
  app/mobile/lib/view/home/homepage.dart
  app/mobile/lib/view/intro/intro.dart
  app/mobile/macos/Flutter/Flutter-Debug.xcconfig
  app/mobile/macos/Flutter/Flutter-Release.xcconfig
  app/mobile/macos/Flutter/GeneratedPluginRegistrant.swift
  app/mobile/macos/Podfile
  app/mobile/macos/Podfile.lock
  app/mobile/macos/Runner.xcodeproj/project.pbxproj
  app/mobile/macos/Runner.xcworkspace/contents.xcworkspacedata
  app/mobile/pubspec.lock
  app/mobile/pubspec.yaml
Labels: enhancement, effort: moderate, mobile

#315 enable validation and authorization for enrollment and course functions
  app/server/src/routes/course/course.controller.js
  app/server/src/routes/course/course.route.js
  app/server/src/routes/course/course.validate.js
  app/server/src/routes/enrollment/enrollment.controller.js
  app/server/src/routes/enrollment/enrollment.route.js
  app/server/src/routes/enrollment/enrollment.validate.js
Labels: backend

#321 remove authorization from get function 'course/:id'
  app/server/src/routes/course/course.route.js
Labels: backend

#320 discussions and notes (basic version)
  app/client/components/Button/Button.jsx
  app/client/components/Note/note.jsx
  app/client/layouts/main/MainLayout.jsx
  app/client/layouts/main/MainLayout.module.scss
  app/client/next.config.js
  app/client/package-lock.json
  app/client/package.json
  app/client/pages/my/spaces/[space_id]/discussions.js
  app/client/pages/my/spaces/[space_id]/events.js
  app/client/pages/my/spaces/[space_id]/notes.js
  app/client/pages/my/spaces/[space_id]/resources.js
  app/client/pages/user/login.js
  app/client/styles/globals.scss
  app/client/styles/my/discussions.module.scss
  app/client/styles/my/events.module.scss
  app/client/styles/my/notes.module.scss
  app/client/styles/my/resources.module.scss
  app/client/yarn.lock
Labels: frontend

#318 Mobile/coursepage
  app/mobile/lib/classes/chapter/chapter.dart
  app/mobile/lib/classes/chapter/chapter.g.dart
  app/mobile/lib/classes/course/course.dart
  app/mobile/lib/classes/course/course.g.dart
  app/mobile/lib/locator.config.dart
  app/mobile/lib/main.dart
  app/mobile/lib/resources/custom_colors.dart
  app/mobile/lib/services/content_service.dart
  app/mobile/lib/services/course_service.dart
  app/mobile/lib/services/locator.dart
  app/mobile/lib/view/course/content_tile.dart
  app/mobile/lib/view/course/coursepage.dart
  app/mobile/lib/view/home/course_tile.dart
  app/mobile/lib/view/home/homepage.dart
  app/mobile/pubspec.lock
  app/mobile/pubspec.yaml
Labels: enhancement, priority: high, effort: moderate, mobile

#328 remove user_id from getCourses validation
  app/server/src/routes/course/course.controller.js
  app/server/src/routes/enrollment/enrollment.controller.js
Labels: backend

#337 [Mobile] Profile Page / Initial Version
  app/mobile/lib/demo/Person.svg
  app/mobile/lib/services/profile_service.dart
  app/mobile/lib/view/dashboard_view.dart
  app/mobile/lib/view/profile.dart
  app/mobile/lib/view/profile/profile.dart
Labels: mobile
